function sayGreeting(){
  let  a = parseInt(document.getElementById("a").value);
  let b = parseInt(document.getElementById("nama1").value);

  let  c = parseInt(document.getElementById("b").value);
  let d = parseInt(document.getElementById("nama2").value);

  let  e = parseInt(document.getElementById("c").value);
  let f = parseInt(document.getElementById("nama3").value);

  let  g = parseInt(document.getElementById("d").value);
  let h = parseInt(document.getElementById("nama4").value);

  let  i = parseInt(document.getElementById("e").value);
  let j = parseInt(document.getElementById("nama5").value);

  let  k = parseInt(document.getElementById("f").value);
  let l = parseInt(document.getElementById("nama6").value);

  let  m = parseInt(document.getElementById("g").value);
  let n = parseInt(document.getElementById("nama7").value);

  let  o = parseInt(document.getElementById("h").value);
  let p = parseInt(document.getElementById("nama8").value);

  let  q = parseInt(document.getElementById("i").value);
  let r = parseInt(document.getElementById("nama9").value);

  let  s = parseInt(document.getElementById("j").value);
  let t = parseInt(document.getElementById("nama10").value);

  let  u = parseInt(document.getElementById("k").value);
  let w = parseInt(document.getElementById("nama11").value);

  let  x = parseInt(document.getElementById("l").value);
  let y = parseInt(document.getElementById("nama12").value);

  let  z = parseInt(document.getElementById("m").value);
  let dd = parseInt(document.getElementById("nama13").value);

  let  cc = parseInt(document.getElementById("n").value);
  let aa = parseInt(document.getElementById("nama14").value);

  let  bb = parseInt(document.getElementById("o").value);
  let ee = parseInt(document.getElementById("nama15").value);

  saya1 = (a + b) / 2;
  saya2 = (c + d) / 2;
  saya3 = (e + f) / 2;
  saya4 = (g + h) / 2;
  saya5 = (i + j) / 2;
  saya6 = (k + l) / 2;
  saya7 = (m + n) / 2;
  saya8 = (o + p) / 2;
  saya9 = (q + r) / 2;
  saya10 = (s + t) / 2;
  saya11 = (u + w) / 2;
  saya12 = (x + y) / 2;
  saya13 = (z + dd) / 2;
  saya14 = (cc + aa) / 2;
  saya15 = (bb + ee) / 2;
  
   let aku    = document.getElementById('rata') 
   let hasil2 = document.getElementById('hasil')
   let hasil5 = document.getElementById('hasil1')
   let hasil1 = document.getElementById('hasil2')
   let hasil6 = document.getElementById('hasil3')
   let hasil4 = document.getElementById('hasil4')
   let hasil7 = document.getElementById('hasil5')
   let hasil8 = document.getElementById('hasil6')
   let hasil9 = document.getElementById('hasil7')
   let hasil10 = document.getElementById('hasil8')
   let hasil11 = document.getElementById('hasil9')
   let hasil12 = document.getElementById('hasil10')
   let hasil13  = document.getElementById('hasil11')
   let hasil14 = document.getElementById('hasil12')
   let hasil15 = document.getElementById('hasil13')
   let hasil16 = document.getElementById('hasil14')

   hasil3 = aku.innerHTML = "Hasil Rata Rata nilai :"
   hasil3 = hasil2.innerHTML = "rata rata nilai PAI :"+ saya1
   hasil3 = hasil5.innerHTML = "rata rata nila PPKN :"+ saya2
   hasil3 = hasil1.innerHTML = "rata rata nilai B.Indonesia :"+ saya3
   hasil3 = hasil6.innerHTML = "rata rata nilai Matematika :"+ saya4  
   hasil3 = hasil4.innerHTML = "rata rata nilai Sejarah Indonesia :"+ saya5
   hasil3 = hasil7.innerHTML = "rata rata nilai Bahasa Inggris :"+ saya6
   hasil3 = hasil8.innerHTML = "rata rata nilai Seni Budaya :"+ saya7
   hasil3 = hasil9.innerHTML = "rata rata nilai PJOK :"+ saya8
   hasil3 = hasil10.innerHTML = "rata rata nilai Prakarya :"+ saya9
   hasil3 = hasil11.innerHTML = "rata rata nilai BTA :"+ saya10
   hasil3 = hasil12.innerHTML = "ata rata nilai Geografi :"+ saya11
   hasil3 = hasil13.innerHTML = "rata rata nilai Ekonomi :"+ saya12
   hasil3 = hasil14.innerHTML = "rata rata nilai Sejarah :"+ saya13
   hasil3 = hasil15.innerHTML = "rata rata nilai Sosiologi :"+ saya14
   hasil3 = hasil16.innerHTML = "rata rata nilai B.Jepang :"+ saya15
 }
